-- 恒慧管方案 A：整库 JSON 存 MySQL
CREATE DATABASE IF NOT EXISTS henghuiguan
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE henghuiguan;

CREATE TABLE IF NOT EXISTS app_store (
  id TINYINT NOT NULL PRIMARY KEY DEFAULT 1,
  payload LONGTEXT NOT NULL COMMENT '整库 JSON（users/projects/tasks/...）',
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
    ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
